[feat] #1 데이터베이스 연동
Leets-Official/MoodMate-BE pull request #2
Opened 2023-11-08 17:04 UTC by leeseobin00

## 1. 무슨 이유로 코드를 변경했나요?
- 데이터베이스 연동을 위한 설정을 추가하였습니다. 
- 프로젝트가 MySQL 데이터베이스와 연결되었습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
- MySQL 데이터베이스와의 연결을 위한 `application.properties` 파일 설정을 완료하였습니다.
- Readme 파일에 환경 변수 내용을 반영하였습니다.
<br>

## 5. 추가 사항
- Issue Template 오타 수정하였습니다.

2023-11-10 14:25 UTC, MinhoJJang requested changes

2023-11-10 14:25 UTC, MinhoJJang commented on README.md
> +```
RDS 생성해놓았기때문에 이걸로 사용하면 됩니다.

마스터 사용자 이름: moody
마스터 암호: moodmate
초기 데이터베이스 이름: moodmate
엔드포인트: leets-itor-moodmate.cal58tltx1bh.ap-northeast-2.rds.amazonaws.com
포트: 3306

2023-11-10 14:25 UTC, MinhoJJang commented on README.md
> +```
Notion에 System Architecture 부분에 설명 있으니 필요하다면 확인해주세요

2023-11-12 15:21 UTC, MinhoJJang approved these changes

2023-11-12 15:22 UTC, merged

2023-11-27 13:52 UTC, leeseobin00 commented on README.md
> +```
감사합니당!!👍🏻