[feat] #57 상대무디 상세조회 api 구현
Leets-Official/MoodMate-BE pull request #57
Opened 2023-12-01 16:18 UTC by jiixon

## 1. 무슨 이유로 코드를 변경했나요?

- 채팅중이 유저의 상대방에 대한 정보를 조회합니다.

<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

현재 지원이(userid =2)와 지원이2(userid = 3)가 같은 채팅방에 있습니다.
지원이(userid =2)가 상대인 지원이2(userid = 3)의 정보를 조회한 경우입니다.

![image](https://github.com/Leets-Official/MoodMate-BE/assets/108799865/f7eb8262-e0d8-46be-a920-1b69e15c3854)

![image](https://github.com/Leets-Official/MoodMate-BE/assets/108799865/f98399c6-70e3-4f99-8a41-a7a5adb16694)

![image](https://github.com/Leets-Official/MoodMate-BE/assets/108799865/b2a6a6a8-ed35-4c9e-807f-2becb7822255)

<br>

## 4. 완료 사항
상대무디 상세조회 API

<br>

## 5. 추가 사항
close #34

2023-12-01 18:08 UTC, MinhoJJang requested changes

2023-12-01 18:08 UTC, MinhoJJang commented on src/main/java/com/moodmate/moodmatebe/domain/chat/repository/RoomRepository.java
> +    Optional<ChatRoom> findByUser1UserIdOrUser2UserId(Long user1Id, Long user2Id);
roomActive가 true 인지 확인하는 것이 필요해 보입니다!

예외 케이스를 설명드리자면, 아래와 같습니다. 

chatRoomDB에는 아래와 같은 데이터가 있다고 가정해보겠습니다.
|user1_id|user2_id|roomActive|설명|
|-|-|-|-|
|11|10|false|어제 매칭됨|
|11|19|true|오늘 매칭됨|
|20|19|false|어제 매칭됨|

```java
Optional<ChatRoom> findByUser1UserIdOrUser2UserId(Long user1Id, Long user2Id);
```
를 SQL로 바꾸면
```sql
SELECT * 
FROM chat_room 
WHERE user1_id = user1Id OR user2_id = user2Id;
```
가 됩니다.

즉, 만약 `findByUser1UserIdOrUser2UserId(11, 11)` 를 하게 되면
chat_room 중 user1_id가 11 이거나, user2_id가 11인 모든 방을 찾게 됩니다. 

즉 리턴되는 값은 아래와 같습니다.
|user1_id|user2_id|roomActive|
|-|-|-|
|11|10|false|
|11|19|true|

그러니까 그냥 11만 있으면 리턴이 됩니다.
하지만 true인 방은 아이디 당 무조건 최대 하나이기 때문에
roomActive가 true인지 아닌지를 검사해주는 로직이 필요합니다.

2023-12-02 01:00 UTC, jiixon commented on src/main/java/com/moodmate/moodmatebe/domain/chat/repository/RoomRepository.java
> +    Optional<ChatRoom> findByUser1UserIdOrUser2UserId(Long user1Id, Long user2Id);
감사합니다!! 수정했습니다 확인부탁드려요!:)

2023-12-02 01:17 UTC, leeseobin00 approved these changes
고생하셨습니다

2023-12-02 02:01 UTC, MinhoJJang approved these changes

2023-12-02 02:02 UTC, merged